FROM node:14.16.0-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM nginx:1.12.-alpine
# <---------------- Here we are running nginx as root user. Dont do it in production --------------> 
COPY --from=build-stage /app/build /usr/share/nginx/html/
EXPOSE 80
ENTRYPOINT [ "nginx" "-g", "daemon off;" ] 
